version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: e9
      POSTGRES_PASSWORD: ethernos
      POSTGRES_DB: leetcode_clone
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: "postgresql://e9:ethernos@db:5432/leetcode_clone"
      QUEUE_URL: "amqp://rabbitmq"
    depends_on:
      - db
      - rabbitmq
    ports:
      - "4000:4000"

  worker:
    build:
      context: ./worker
    environment:
      QUEUE_URL: "amqp://rabbitmq"
    depends_on:
      - rabbitmq

volumes:
  db_data: