# Worker Dockerfile
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose no port since it doesn't serve HTTP
CMD ["node", "index.js"]
